### PR TITLE
Generalize interfaces to allow channel-agnostic IO

### PR DESCRIPTION
**Pull request by ghost**
This PR changes the library such that a more general interface `AsyncByteChannel` is used for communication rather than `AsynchronousSocketChannel`. This allows for using capnproto RPC on custom channels other than raw TCP sockets.

I've tested this by using this library to send RPC packets over HTTP2 data frames to cloudflare's argo tunnels edge nodes (which uses Golang I think) and I was able to successfully communicate with them.

This also fixes tests units that failed to pass previously, uses "gmake" to compile on OpenBSD instead of "make", and specify JitPack to use JDK 11 instead when compiling the project.

### CODE REVIEW

**Comment by vaci** [comment]
Could this generalisation also be achieved by expanding to the `java.nio.channels.AsynchronousByteChannel` interface rather than `AsynchronousSocketChannel` ? It's nicer if the interfaces can accept standard Java types where possible, rather than having to wrap  what would otherwise be common cases such as sockets.

**Comment by ghost** [comment]
It may be possible but it requires further changes to the codebase. `AsynchronousByteChannel` doesn't have a function for performing read/write with a specified timeout, which is why I created `AsyncByteChannel` for this purpose.

It may be possible to change the existing codebase to use async rw without specifying timeout, but the truth is that I hadn't looked into the code that deep so I came up with this solution instead. I will take a second look and see if is possible when i'm free.

**Comment by vaci** [comment]
it's been a while since I looked at this code, but I suspect that read or write timeouts aren't actually used. The async calls in Serialize.java that accept a timeout could just have the timeout parameter removed.

**Comment by ghost** [comment]
Okay, I've changed the code such that `AsynchronousByteChannel` is used instead. Test units pass and I've also tested it in practice with one of my project.

**Comment by vaci** [comment]
I've split up your PR and applied the obvious fixes separately.

The patch to use AsynchronousByteChannels all seems fine, except for AsynchronousByteListenChannel which feels like it is beyond the scope of the capnproto library to implement - the code is implementing server socket behaviour for things that are not sockets, and I'm inclined to punt that to the caller to deal with.

Started a new PR to track this work: https://github.com/vaci/capnproto-java-rpc/pull/32

**Pull request closed without merging**
